/**
 * Built-in reading library: short Moroccan Darija stories from A1 to C1,
 * written in Latin script (the everyday "Arabizi" spelling most Darija
 * speakers actually read/write online), each with an English glossary of key
 * vocabulary and a post-reading quiz covering vocabulary, comprehension and
 * subject/theme.
 */

import type { RawStory } from './storyUtils';

export const DARIJA_RAW_STORIES: RawStory[] = [
  /* --------------------------------- A1 --------------------------------- */
  {
    id: 'da1-nhar-fhayat-youssef',
    title: 'Nhar dyal Youssef',
    translatedTitle: 'A day of Youssef',
    level: 'A1',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Daily routine',
    summary: 'Youssef walks us through a typical day, from breakfast to a family dinner.',
    paragraphs: [
      'Youssef saken f Dar Lbeida. 3ando tes3tach 3am w houwa tilmid. Koll sbah kayfiq Youssef fse3a sab3a.',
      'Awel haja, kayakol Youssef khobz bzebda w kayshreb atay. Mn ba3d kaytlbes bsor3a.',
      'Youssef kaymshi lmadrasa bttomobil dyal baba. Lmadrasa qriba mn dar.',
      'Fnhar, kayqra Youssef m3a shabo fl9ism. Houma kayhedro bddarija w shwiya bfransawiya.',
      'Fllil, kayakol Youssef m3a l3ayla dyalo. Mamah katayeb tajine. Youssef kay7eb tajine bezzaf!',
    ],
    glossary: [
      { term: 'kayfiq', translation: 'wakes up' },
      { term: 'kayakol', translation: 'eats' },
      { term: 'khobz', translation: 'bread' },
      { term: 'atay', translation: 'tea' },
      { term: 'kaytlbes', translation: 'gets dressed' },
      { term: 'tomobil', translation: 'car' },
      { term: 'lmadrasa', translation: 'school' },
      { term: 'shabo', translation: 'his friends' },
      { term: 'tajine', translation: 'tagine' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'kayfiq' mean?", choices: ['wakes up', 'sleeps', 'eats', 'studies'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'tomobil' mean?", choices: ['car', 'bicycle', 'bus', 'train'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What time does Youssef wake up?', choices: ['6:00', '7:00', '8:00', '9:00'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'How does Youssef get to school?', choices: ['walking', "by his dad's car", 'by bus', 'by bike'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What does his mother cook at night?', choices: ['couscous', 'tagine', 'soup', 'bread'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A trip to Casablanca', "Youssef's daily routine", 'A school exam', 'A family wedding'], correctIndex: 1 },
    ],
  },
  {
    id: 'da1-lai2ila-souad',
    title: "L3ayla dyal Souad",
    translatedTitle: "Souad's family",
    level: 'A1',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Family',
    summary: 'Souad introduces her big family and their Friday tradition together.',
    paragraphs: [
      'Souad 3andha 3ayla kbira. 3andha jouj khout w kht wahda. Baba w mama dyalha smiythom Ahmed w Fatima.',
      'Khoha lkbir smito Rachid. Rachid 3ando tlatin 3am w kaykhdem fbank.',
      'Khtha smitha Layla. Layla mezyana bezzaf w katqra ttob fljami3a.',
      'Nhar jjem3a, koll l3ayla katakol m3a jdod. Jedda katayeb harira bnina.',
      'Souad kat7eb tel3eb m3a khoha sghir, Omar. Omar 3ando tes3 snin walakin kayel3eb mezyan bezzaf.',
    ],
    glossary: [
      { term: 'khout', translation: 'siblings / brothers' },
      { term: 'kht', translation: 'sister' },
      { term: 'bank', translation: 'bank' },
      { term: 'ttob', translation: 'medicine' },
      { term: 'jdod', translation: 'grandparents' },
      { term: 'harira', translation: 'harira soup' },
      { term: 'bnina', translation: 'delicious' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'kht' mean?", choices: ['sister', 'mother', 'aunt', 'cousin'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'bank' mean?", choices: ['bank', 'school', 'hospital', 'market'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'How many siblings does Souad have in total?', choices: ['1', '2', '3', '4'], correctIndex: 2 },
      { id: 'q4', type: 'comprehension', prompt: 'What does Layla study?', choices: ['Law', 'Medicine', 'Engineering', 'Art'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'Who cooks harira on Fridays?', choices: ["Souad's mother", 'the grandmother', 'Layla', 'Rachid'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ["Souad's school", "Souad's family", 'A bank job', 'A trip abroad'], correctIndex: 1 },
    ],
  },
  {
    id: 'da1-fessouq',
    title: 'Fsouq',
    translatedTitle: 'At the market',
    level: 'A1',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Shopping & food',
    summary: "Khadija's Saturday routine of buying fresh food at the local market.",
    paragraphs: [
      'Nhar sebt, Khadija katmshi lsouq m3a qoffa dyalha. Souq qrib mn dar w kayhal bekri.',
      'Khadija katshri lfawakih ttriya: tfah hmer, banane sfer, w limoune hlou. Lfawakih machi ghalya.',
      'Katshri ayssan lkhodra: tomatich, basla, w btata. Lbay3 dyal lkhodra mezyan bezzaf m3a Khadija.',
      'Fsouq kayn farran sghir. Khadija dima katshri khobz tri w shhal mn mra hlwa bchokola.',
      'Mli katsali mn chra, Khadija katrja3 ldar w katayeb lghda l3ayla. Kolshi tri w bnin!',
    ],
    glossary: [
      { term: 'qoffa', translation: 'basket' },
      { term: 'lfawakih', translation: 'fruits' },
      { term: 'tfah', translation: 'apples' },
      { term: 'lkhodra', translation: 'vegetables' },
      { term: 'lbay3', translation: 'the seller' },
      { term: 'farran', translation: 'bakery' },
      { term: 'lghda', translation: 'lunch' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'qoffa' mean?", choices: ['basket', 'bag', 'box', 'cart'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'farran' mean?", choices: ['bakery', 'pharmacy', 'butcher shop', 'market'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What day does Khadija go to the market?', choices: ['Friday', 'Saturday', 'Sunday', 'Monday'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What does she buy at the bakery besides bread?', choices: ['a sweet with chocolate', 'cookies', 'a sandwich', 'ice cream'], correctIndex: 0 },
      { id: 'q5', type: 'comprehension', prompt: 'How does the vegetable seller treat her?', choices: ['rudely', 'indifferently', 'kindly', 'impatiently'], correctIndex: 2 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A doctor visit', 'A Saturday market trip', 'Cooking a cake', 'A family trip'], correctIndex: 1 },
    ],
  },
  {
    id: 'da1-ta3aruf',
    title: "Ta3aruf",
    translatedTitle: 'Getting to know each other',
    level: 'A1',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Greetings & introductions',
    summary: 'Munir meets Thomas, who came to Marrakech to learn Darija.',
    paragraphs: [
      'Salam! Smiti houwa Mounir. 3andi 3achrin 3am w saken fMarrakech. Farhan bezzaf nt3aref 3lik.',
      'Mounir kayhder l3arabiya w lfransawiya, w kayqra daba lingliziya fjami3a dyal Marrakech.',
      'Sahbo jdid smito Thomas, ja mn Spanya bash yqra l3arabiya ddarija.',
      'Mounir w Thomas kaytlaqaw koll nhar flqahwa bash yhedro w yat3allmo mn ba3diyathom.',
      "Thomas kayqol lMounir: 'Choukran bezzaf 3la lmosa3ada dyalek.' W Mounir kayjaweb: 'Marhba bik, hna shab daba!'",
    ],
    glossary: [
      { term: 'farhan', translation: 'happy' },
      { term: 'kayhder', translation: 'speaks' },
      { term: 'lqahwa', translation: 'the café' },
      { term: 'yat3allmo', translation: 'they learn' },
      { term: 'lmosa3ada', translation: 'the help' },
      { term: 'shab', translation: 'friends' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'farhan' mean?", choices: ['happy', 'tired', 'sad', 'angry'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'lqahwa' mean?", choices: ['café', 'school', 'market', 'house'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'Where is Munir from?', choices: ['Rabat', 'Marrakech', 'Casablanca', 'Fes'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'Where is Thomas from?', choices: ['France', 'Spain', 'Italy', 'Portugal'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'Why is Thomas learning Darija?', choices: ['for work', 'to study it at university', 'for a trip', 'for his family'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['Two friends learning from each other at a café', 'A business trip', 'A market day', 'A wedding'], correctIndex: 0 },
    ],
  },
  {
    id: 'da1-alwan-fdar',
    title: 'Lalwan fddar',
    translatedTitle: 'Colors at home',
    level: 'A1',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Colors & everyday objects',
    summary: "The colorful objects around the Idrissi family's home.",
    paragraphs: [
      'Dar l3a2ilat Idrissi fiha alwan bezzaf. Bab kbir w lono zreq.',
      'Fsalon, korsi lono hmer w tabla lonha bonni. Sitayer sofra w zwinin.',
      'Fkozina, 7ayt lono byad w forn lono rmadi. Lwani dyal atay khdra.',
      'Bent Idrissi, Amal, 3andha pyjama wardiya w katbghi lalwan zwinin bezzaf.',
      "Amal katqol: 'Ddar dyalna fiha qws qzah!' W koll l3ayla katdhek m3aha.",
    ],
    glossary: [
      { term: 'zreq', translation: 'blue' },
      { term: 'hmer', translation: 'red' },
      { term: 'sofra', translation: 'yellow' },
      { term: 'khdra', translation: 'green' },
      { term: 'byad', translation: 'white' },
      { term: 'rmadi', translation: 'gray' },
      { term: 'qws qzah', translation: 'rainbow' },
      { term: 'katdhek', translation: 'laughs' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'zreq' mean?", choices: ['blue', 'red', 'green', 'yellow'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'qws qzah' mean?", choices: ['rainbow', 'sky', 'sun', 'cloud'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What color is the door?', choices: ['red', 'blue', 'green', 'white'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What color are the curtains?', choices: ['white', 'yellow', 'gray', 'brown'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What does Amal say about the house?', choices: ["it's too small", 'it has a rainbow of colors', 'it needs painting', "it's very old"], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A family renovating their house', "The colorful objects around a family's home", 'A trip to buy furniture', 'A birthday party'], correctIndex: 1 },
    ],
  },

  /* --------------------------------- A2 --------------------------------- */
  {
    id: 'da2-3otla-chefchaouen',
    title: "Nhar l3otla f Chefchaouen",
    translatedTitle: 'A day off in Chefchaouen',
    level: 'A2',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Weekend trip',
    summary: 'Sara and her friends spend a memorable weekend in the blue city.',
    paragraphs: [
      'Sif lli fat, Sara w shabatha qarraw ymshiw lChefchaouen. Khrjo mn Dar Lbeida nhar jjem3a fseba7.',
      'Mli wslo, shafo lmdina zerqa w bqaw mabhourin. Kraw dar zwina qriba mn souq.',
      'Nhar sebt, tmashaw flezenqa dyeqin w shraw hwayej taqlidiya. Sara shrat jellaba zerqa.',
      'Fl3achiya, klaw tajine ldid fmat3am sghir. Sahebtha Rim tlbat couscous w 3jbha bezzaf.',
      'Billil, jelso fouq stah w shafo njoum. Kant lila matatnsach.',
      'Nhar lhad, qbel ma yerj3o ldar, shraw shwiya dyal hwayej tedkar mn rrehla.',
    ],
    glossary: [
      { term: 'mabhourin', translation: 'amazed' },
      { term: 'zenqa dyeqin', translation: 'the narrow alleys' },
      { term: 'jellaba', translation: 'djellaba' },
      { term: '3jbha', translation: 'she liked it' },
      { term: 'stah', translation: 'the rooftop' },
      { term: 'njoum', translation: 'the stars' },
      { term: 'tedkar', translation: 'souvenir' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'mabhourin' mean?", choices: ['amazed', 'tired', 'lost', 'hungry'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'stah' mean?", choices: ['rooftop', 'basement', 'garden', 'kitchen'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'When did they leave Casablanca?', choices: ['Thursday', 'Friday morning', 'Saturday night', 'Sunday'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What did Sara buy?', choices: ['a bag', 'a blue djellaba', 'shoes', 'a hat'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What did they do at night on the rooftop?', choices: ['cooked dinner', 'watched the stars', 'danced', 'read books'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A business trip', 'A memorable weekend trip to Chefchaouen', 'A cooking competition', 'Moving to a new city'], correctIndex: 1 },
    ],
  },
  {
    id: 'da2-3id-milad-mfaja2a',
    title: "3id milad blmfaja2a",
    translatedTitle: 'The surprise birthday',
    level: 'A2',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Friendship & celebration',
    summary: "Mariam's friends secretly plan a surprise party for her birthday.",
    paragraphs: [
      'Kan 3id milad dyal Mariam, w shabatha bghaw ydiro liha hafla blmfaja2a. Hatta wahed ma qal liha walou.',
      'Nadia shrat balonat w zina dyal lalwan. Salma tayebt gato kbir bchokola.',
      'Nhar hafla, shabat tkhebbaw fsalon qbel ma tji Mariam mn khedma.',
      "Mli hallat Mariam bab, kolshi sah 'Mfaja2a!' w hiya frhat bezzaf, ghir qrib tebki mn ferha.",
      'Rq9o llil kamel w klaw gato. Mariam qalat hadi kant ahsen 3id milad f7ayatha.',
      'F akher hafla, Mariam shokrat koll shabatha 3la t3eb w lmhabba lli wraweha liha.',
    ],
    glossary: [
      { term: 'balonat', translation: 'balloons' },
      { term: 'zina', translation: 'decorations' },
      { term: 'gato', translation: 'cake' },
      { term: 'tkhebbaw', translation: 'they hid' },
      { term: 'sah', translation: 'shouted' },
      { term: 'frhat', translation: 'she got happy' },
      { term: 'shokrat', translation: 'thanked' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'balonat' mean?", choices: ['balloons', 'flowers', 'candles', 'gifts'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'tkhebbaw' mean?", choices: ['they hid', 'they danced', 'they left', 'they cooked'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'Who made the cake?', choices: ['Mariam', 'Nadia', 'Salma', "Mariam's mother"], correctIndex: 2 },
      { id: 'q4', type: 'comprehension', prompt: 'What flavor was the cake?', choices: ['vanilla', 'chocolate', 'lemon', 'caramel'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'How did Mariam react?', choices: ['she got angry', 'she was confused', 'she got very happy and almost cried', 'she left'], correctIndex: 2 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A cooking class', 'A surprise birthday party organized by friends', 'A work meeting', 'A trip abroad'], correctIndex: 1 },
    ],
  },
  {
    id: 'da2-atay-m3a-jiran',
    title: 'Atay m3a ljiran',
    translatedTitle: 'Tea with the neighbors',
    level: 'A2',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Community & hospitality',
    summary: 'A weekly tea gathering becomes a beloved neighborhood tradition.',
    paragraphs: [
      'Koll nhar jem3a, Lalla Zahra kat3zem ljiran dyalha 3la atay fddar.',
      'Hiya kathder atay bnna3na3 w hlawiyat maghribiya b7al chebakia w ghriba.',
      'Ljiran kayjiw m3a wlad dyalhom, w drari kayel3bo flhouch waqt ma kbar kayhedro.',
      'Nhar mn ayyam, Lalla Zahra hkat qissa qdima 3la houma w 3la jdod dyalha.',
      'Ljiran 3jbethom qissa bezzaf, w qalo bash yjiw koll jem3a yesm3o hkayat jdad.',
      'Mn hadak nhar, jem3a wllat nhar mmayez l3a2ilat dyal houma kamla.',
    ],
    glossary: [
      { term: 't3zem', translation: 'invites' },
      { term: 'nna3na3', translation: 'mint' },
      { term: 'drari', translation: 'the kids' },
      { term: 'lhouch', translation: 'the courtyard' },
      { term: 'hkat', translation: 'told / narrated' },
      { term: 'houma', translation: 'the neighborhood' },
      { term: 'mmayez', translation: 'special' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'lhouch' mean?", choices: ['courtyard', 'roof', 'kitchen', 'street'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'houma' mean?", choices: ['neighborhood', 'market', 'mosque', 'school'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What day does Lalla Zahra invite the neighbors?', choices: ['Thursday', 'Friday', 'Saturday', 'Sunday'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What does she serve?', choices: ['coffee and bread', 'mint tea and Moroccan sweets', 'juice and cake', 'soup'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What did Lalla Zahra tell one day?', choices: ['a joke', 'an old story about the neighborhood', 'a recipe', 'a poem'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A weekly gathering that becomes a beloved neighborhood tradition', 'A cooking competition', 'A wedding celebration', 'A family argument'], correctIndex: 0 },
    ],
  },
  {
    id: 'da2-tariq-lhamam',
    title: 'Triq lhammam',
    translatedTitle: 'A trip to the hammam',
    level: 'A2',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Daily life & tradition',
    summary: 'A weekly hammam tradition shared between two sisters.',
    paragraphs: [
      'Nhar lkhmis, Fatima katmshi lhammam m3a khtha sghira. Hadi 3ada dyal koll jem3a 3endhom.',
      'Kayjibo m3ahom saboun beldi w lkiss w shampwan. Hammam dima mezdhem shwiya bnnisa.',
      'Fatima katehes brraha bezzaf mn ba3d ma katkhrej mn hammam. Jeld kaywalli nqi w tri.',
      'Mn ba3d hammam, kaymshiw yshrbo 3asir lbertqal ttaza fhanout qrib.',
      "Khtha sghira katqol liha: 'Hammam howa jjez2 lmofaddal 3endi mn simana.'",
      "Fatima katdhek w katqol: '3endi hatta ana, khosousan mli konkono m3a ba3diyatna.'",
    ],
    glossary: [
      { term: 'hammam', translation: 'the hammam / public bathhouse' },
      { term: 'saboun beldi', translation: 'traditional soap' },
      { term: 'mezdhem', translation: 'crowded' },
      { term: 'nqi', translation: 'clean' },
      { term: '3asir lbertqal', translation: 'orange juice' },
      { term: 'mofaddal', translation: 'favorite' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'hammam' mean?", choices: ['hammam', 'market', 'garden', 'mosque'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'nqi' mean?", choices: ['clean', 'tired', 'cold', 'dirty'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What day do they go to the hammam?', choices: ['Wednesday', 'Thursday', 'Friday', 'Saturday'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What do they bring with them?', choices: ['towels only', 'traditional soap', 'exfoliating glove and shampoo', 'nothing'], correctIndex: 2 },
      { id: 'q5', type: 'comprehension', prompt: 'What do they do after the hammam?', choices: ['go home immediately', 'drink fresh orange juice nearby', 'cook dinner', 'go shopping'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A weekly hammam tradition shared between two sisters', 'A trip to the market', 'A family argument', 'A cooking lesson'], correctIndex: 0 },
    ],
  },
  {
    id: 'da2-telifon-m3a-sahbti',
    title: 'Telefon m3a sahbti',
    translatedTitle: 'A phone call with my friend',
    level: 'A2',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Friendship & communication',
    summary: 'Hind and Lubna keep their friendship alive through weekly calls after Hind moves to Canada.',
    paragraphs: [
      'Mli hajrat Hind lKanada, w3dat sahebtha Lubna anha ghadi t3ayet liha koll simana.',
      'F awel 3aita, Hind hkat 3la lmdina jdida: lberd, nnas, w khedma jdida dyalha.',
      'Lubna frhat bezzaf tesma3 sawt sahebtha, w qalat liha kifach l7al flmghrib.',
      'M3a lwaqt, Hind bdat thki 3la sahb flkhedma smito Karim, w Lubna hssat bshi haja fsawtha.',
      "B3d 3am, Hind 3aytat lsahebtha w qalat liha: 'Karim tleb yeddi biya, w bghit tji lKanada l3ers.'",
      "Lubna dhekat w qalat: 'Ma kont ntsenna ila had lkhbar! Ghadi nji, matkhafich.'",
    ],
    glossary: [
      { term: 'hajrat', translation: 'emigrated' },
      { term: 't3ayet', translation: 'calls / phones' },
      { term: 'lberd', translation: 'the cold' },
      { term: 'sawt', translation: 'voice' },
      { term: 'l3ers', translation: 'the wedding' },
      { term: 'matkhafich', translation: "don't worry" },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 't3ayet' mean?", choices: ['calls', 'writes', 'visits', 'forgets'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'l3ers' mean?", choices: ['wedding', 'birthday', 'graduation', 'funeral'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'Why did Hind move?', choices: ['to study', 'for her job', 'to be with family', 'to retire'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'Who is Karim?', choices: ["Hind's brother", "Hind's coworker", "Lubna's husband", "Hind's neighbor"], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What news does Hind share at the end?', choices: ["she's coming back for good", 'Karim proposed and she wants Lubna at the wedding', 'she lost her job', "she's moving again"], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A friendship kept alive through weekly calls as Hind builds a new life abroad', 'A business trip gone wrong', 'A cooking exchange', 'A mystery about a missing letter'], correctIndex: 0 },
    ],
  },

  /* --------------------------------- B1 --------------------------------- */
  {
    id: 'db1-khadma-jdida-yassmine',
    title: 'Lkhedma jdida dyal Yassmine',
    translatedTitle: "Yasmine's new job",
    level: 'B1',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Work & belonging',
    summary: 'Yasmine overcomes her nerves and finds her place on a new team.',
    paragraphs: [
      'Mn ba3d ma qelbat 3la khedma lmodda dyal chhor, Yassmine flakhir lqat blasa fcharika dyal technologia. Kant khayfa bezzaf mn awel nhar dyalha.',
      'Hatta ila kan 3andha tajriba kdesigner, 3omrha ma khedmat m3a fariq kbir b7al hada. Kant khayfa matndemejch m3a zomala2 jdad.',
      'Awel nhar, ra2is dyalha 3arrefha bfariq w shrah liha lmasharia3 lli ghadiyin ykhedmo 3lihom fhad tlata chhor jayin.',
      'M3a mrour lasabi3, Yassmine hssat belli zomala2 dyalha kano mezyanin bezzaf w dima mosta3dín y3awnoha.',
      'Shwiya bshwiya, bdat thess rasha jozz2 mn fariq. Hatta eqtre7at fikra bash yhesno tasmim dyal ttatbiq lli kant charika katkhdem 3lih.',
      'F akher tlata chhor, ra2is dyalha hennaha qeddam jami3. Yassmine hssat blfakhr li2anha qedrat tatghaleb 3la khof dyalha.',
    ],
    glossary: [
      { term: 'qelbat 3la', translation: 'searched for' },
      { term: 'khayfa', translation: 'afraid' },
      { term: 'matndemejch', translation: "doesn't fit in" },
      { term: 'ra2is', translation: 'the boss' },
      { term: 'zomala2', translation: 'the colleagues' },
      { term: 'mosta3dín', translation: 'willing / ready' },
      { term: 'eqtre7at', translation: 'proposed' },
      { term: 'lfakhr', translation: 'pride' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'matndemejch' mean?", choices: ['to not fit in', 'to argue', 'to resign', 'to travel'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'mosta3dín' mean?", choices: ['willing / ready', 'tired', 'angry', 'confused'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: "What was Yasmine's profession before?", choices: ['Engineer', 'Designer', 'Accountant', 'Teacher'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What worried her most?', choices: ['the salary', 'not fitting in with a large team', 'the commute', 'the hours'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What did she propose?', choices: ['a marketing plan', "an idea to improve the app's design", 'a hiring process', 'a team trip'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['Yasmine overcoming her fears while adapting to a new job', 'A company going bankrupt', 'A failed interview', 'A team trip abroad'], correctIndex: 0 },
    ],
  },
  {
    id: 'db1-brya-mn-fransa',
    title: 'Briya mn Fransa',
    translatedTitle: 'A letter from France',
    level: 'B1',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Friendship & distance',
    summary: 'Amina and Salma keep their friendship alive through letters as Amina builds a new life in France.',
    paragraphs: [
      'Mli hajrat Amina lFransa 3la khater khedma, w3dat sahebtha lghalya, Salma, belli ghadi tekteb liha lbrayat 3iwad matb3ath ghir rasa2il qsira.',
      'F awel briya dyalha, Amina wasfat mdina Paris bhamas kbir: lalwan, makla, w tyba dyal nas lli t3arfat 3lihom.',
      'Salma jawbat w hkat liha akhbar mdina dyalhom, w e3trfat belli katwehesh sahebtha bezzaf hatta ila kant farhana 3liha.',
      'M3a lwaqt, lbrayat dyal Amina bdaw yhedro 3la zamil flkhedma smito Youssef, lli kant katqdi m3ah waqt kter fkter.',
      'Salma hssat bttabdil flbrayat, w fahmat belli sahebtha wq3at flhob, hatta ila Amina maqaltha mobacharatan.',
      'B3d 3am, Amina ketbat akher briya t3len fiha belli ghadi tatzewwej Youssef fParis, w kattmenna an Salma tji l3ers.',
    ],
    glossary: [
      { term: 'hajrat', translation: 'emigrated' },
      { term: 'wasfat', translation: 'described' },
      { term: 'hamas', translation: 'enthusiasm' },
      { term: 'e3trfat', translation: 'admitted' },
      { term: 'katwehesh', translation: 'misses (someone)' },
      { term: 'wq3at flhob', translation: 'fell in love' },
      { term: 'l3ers', translation: 'the wedding' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'katwehesh' mean?", choices: ['misses', 'forgets', 'visits', 'invites'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'l3ers' mean?", choices: ['wedding', 'birthday', 'graduation', 'funeral'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'Why did Amina move?', choices: ['to study', 'for her job', 'family', 'retirement'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'Who is Youssef?', choices: ["Amina's brother", "Amina's coworker", "Salma's husband", "Amina's neighbor"], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'How did Salma realize Amina was in love?', choices: ['Amina told her directly', 'she noticed the change in the letters', 'Youssef told her', 'she visited Paris'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A friendship kept alive through letters as Amina builds a new life in France', 'A business trip gone wrong', 'A cooking exchange', 'A mystery about a missing letter'], correctIndex: 0 },
    ],
  },
  {
    id: 'db1-lghz-lqat-dae3',
    title: 'Lghz lqet ddaye3',
    translatedTitle: 'The mystery of the lost cat',
    level: 'B1',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Mystery',
    summary: 'A woman solves the mystery of her missing cat — and finds a lost ring along the way.',
    paragraphs: [
      'Nhar mn seba7, Lalla Khadija lqat belli qet dyalha, Sabrout, dda3. Qelbat fddar kamla walakin malqatch hatta ather dyalo.',
      'Qelqana bezzaf, qerrat tesqsi ljiran wach shafouh. Jar dyal taht qal liha belli sma3 sawt mwaw fllil.',
      'Bhad lkhit, Lalla Khadija qelbat fserdab dyal 3imara, blasa mdelma 3omrha madkhlathach mn qbel.',
      'Tema, bin lkartounat qdima, lqat Sabrout mhaser mora khizana. Kan bda belli bqa mhaser bla ma yebghi.',
      'Mli 7errato, shafat belli qet 3ando shi haja tlma3 flfom dyalo: khatem sghir kaywalli dyal shi jar akhor.',
      'Lalla Khadija qerrat tesqsi f3imara kamla hatta talqa sahb khatem, w hakadha hallat jouj lghaz fnhar wahed.',
    ],
    glossary: [
      { term: 'dda3', translation: 'disappeared' },
      { term: 'qelqana', translation: 'worried' },
      { term: 'lkhit', translation: 'clue' },
      { term: 'serdab', translation: 'basement' },
      { term: 'mhaser', translation: 'trapped' },
      { term: 'khatem', translation: 'ring' },
      { term: 'sahb', translation: 'owner' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'serdab' mean?", choices: ['basement', 'attic', 'garden', 'roof'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'lkhit' mean?", choices: ['clue', 'key', 'letter', 'photo'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'Who gave the first clue?', choices: ['a police officer', 'the neighbor downstairs', 'her sister', 'the doorman'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'Where was the cat found?', choices: ['on the roof', 'in the basement behind a cabinet', 'in the garden', "at a neighbor's"], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What did the cat have in its mouth?', choices: ['food', 'a small ring', 'a toy', 'a key'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A woman solving the mystery of her missing cat and finding a lost ring', 'A robbery', "A vet's daily routine", 'Moving to a new city'], correctIndex: 0 },
    ],
  },
  {
    id: 'db1-thdir-l3ars',
    title: 'Thdir l3ers',
    translatedTitle: 'Preparing the wedding',
    level: 'B1',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Family & tradition',
    summary: "A family comes together with love to prepare Naima's wedding.",
    paragraphs: [
      'Chhar qbel l3ers dyalha, Naima w 3a2ilatha bdaw yhedro lkolshi bttafsil. Kant farhana bezzaf walakin hassa bddaght.',
      'Mama dyalha kant mas2oula 3la lhalawiyat taqlidiya, w khala kant katshri qeftan w zina dyal dar.',
      'Naima kant khayfa maykemmelch kolshi flwaqt, khosousan qeftanha kan lazm ytsale7 3end khayata.',
      'Youmayn qbel l3ers, koll 3a2ila tjam3at bash t3awen ftahdir makla w zina. Jeddtha hkat liha qssas 3la l3ers dyalha hiya.',
      'Nhar l3ers, Naima lebsat qeftan lakhdar jmil w dkhlat wost zgharit dyal 3a2ila w shabat.',
      'Mn ba3d kolshi, Naima fahmat belli ahem haja machi kant ttandim kamel, walakin lmhabba lli jam3at 3a2ila kamla.',
    ],
    glossary: [
      { term: 'l3ers', translation: 'the wedding' },
      { term: 'ddaght', translation: 'the stress' },
      { term: 'qeftan', translation: 'the kaftan' },
      { term: 'khayata', translation: 'the tailor' },
      { term: 'tjam3at', translation: 'gathered' },
      { term: 'zgharit', translation: 'ululations' },
      { term: 'ttandim', translation: 'the organization' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'qeftan' mean?", choices: ['kaftan', 'hat', 'shoes', 'scarf'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'zgharit' mean?", choices: ['ululations', 'tears', 'songs', 'applause'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'Who was responsible for the sweets?', choices: ['Naima', 'her mother', 'her aunt', 'the tailor'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What worried Naima the most?', choices: ['the guest list', 'her kaftan not being ready in time', 'the food', 'the music'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What did the grandmother do two days before?', choices: ['cooked alone', 'told stories about her own wedding', 'left the house', 'refused to help'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A family coming together with love to prepare a wedding', 'A business deal', 'A trip abroad', 'A cooking competition'], correctIndex: 0 },
    ],
  },
  {
    id: 'db1-intiqal-lhouma-jdida',
    title: 'Lentiqal lhouma jdida',
    translatedTitle: 'Moving to a new neighborhood',
    level: 'B1',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Change & belonging',
    summary: 'A family adjusting to — and finding belonging in — a new neighborhood in Rabat.',
    paragraphs: [
      'Mli entqlat 3a2ilat Ben3ali lhouma jdida fRabat, kano khayfin maytaqlemoch m3a ljiran jdad.',
      'Weld lkbir, Soufiane, kan hzin 3la shab qdam dyalo w makanch bagha ybeddel lmadrasa.',
      'F awel simana, jarthom Lalla Habiba jat tsellem 3lihom w jabat lihom tbeq dyal rfissa, w had shi farrah 3a2ila bezzaf.',
      'Shwiya bshwiya, Soufiane t3arraf 3la derri jdid flhouma smito Anas, w bdaw yel3bo lkora koll 3achiya.',
      'Walid dyal 3a2ila hess belli houma jdida fiha nas mezyanin w mt3awnin, b7al houma qdima bddabt.',
      "B3d chehrayn, Soufiane qal lbaba dyalo: 'Daba had houma wllat b7al darna lasliya.' W koll 3a2ila frhat bhad lklam.",
    ],
    glossary: [
      { term: 'entqlat', translation: 'moved' },
      { term: 'maytaqlemoch', translation: 'to not adapt' },
      { term: 'hzin', translation: 'sad' },
      { term: 'rfissa', translation: 'rfissa (a Moroccan dish)' },
      { term: 'mt3awnin', translation: 'cooperative / helpful' },
      { term: 'derri', translation: 'boy / kid' },
      { term: 'lkora', translation: 'football' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'maytaqlemoch' mean?", choices: ['to not adapt', 'to not sleep', 'to not eat', 'to not travel'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'lkora' mean?", choices: ['football', 'basketball', 'tennis', 'running'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'Who welcomed the family first?', choices: ['a shopkeeper', 'the neighbor Lalla Habiba', 'the school principal', 'a police officer'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What did Sofiane feel at first?', choices: ['excited', 'sad about leaving his old friends', 'angry at his parents', 'indifferent'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'Who did Sofiane become friends with?', choices: ['a teacher', 'a boy named Anas', 'his cousin', 'a shopkeeper'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A family adjusting to and finding belonging in a new neighborhood', 'A business relocation', 'A cooking lesson', 'A wedding preparation'], correctIndex: 0 },
    ],
  },

  /* --------------------------------- B2 --------------------------------- */
  {
    id: 'db2-qarar-lmohandiss',
    title: 'Qrar lmohandes',
    translatedTitle: "The engineer's decision",
    level: 'B2',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Ethics & work',
    summary: 'An engineer faces an ethical dilemma between preserving history and turning a profit.',
    paragraphs: [
      'Tarek khdem khemstach 3am kmohandes fnfs lmaktab, kaysemmem bnayat qlil ma kayshoufha kamla b3aynih.',
      'Nhar mn ayyam, 3rdo 3lih ydir mashro3 tmou7: tarmim masrah qdim lli mdina bghat thawlo lmarkaz thaqafi.',
      "Moshkil kan belli bash ykoun mashro3 mor'bih, charika kant mosarra ymhaw shi 3anasir tarikhiya mn wajha asliya.",
      'Tarek hess belli lqoboul bhad shorout ghadi ykhoun rouh lbenaya, hatta ila rafd kan ghadi yhedded blasa dyalo fcharika.',
      'B3d bezzaf dyal llyali bla n3as, qerrar yeqtare7 hal akhor: yhafed 3la wajha kima hiya w ynqes lmasarif fblayes okhra mabantch bezzaf.',
      "Bsah, lbaladiya qeblat leqtirah dyalo bferha kbira, w masrah lmoramam wlla mashro3 lli Tarek kan lakthar fakhour bih.",
    ],
    glossary: [
      { term: 'kaysemmem', translation: 'designs' },
      { term: 'tarmim', translation: 'restoration' },
      { term: "mor'bih", translation: 'profitable' },
      { term: 'wajha', translation: 'the facade' },
      { term: 'ykhoun', translation: 'would betray' },
      { term: 'yeqtare7', translation: 'proposes' },
      { term: 'lbaladiya', translation: 'the municipality' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'wajha' mean?", choices: ['facade', 'foundation', 'roof', 'hallway'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: `What does "mor'bih" mean?`, choices: ['profitable', 'historic', 'dangerous', 'modern'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What project was Tariq offered?', choices: ['a stadium', 'restoring an old theater', 'a mall', 'his own house'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What did the company want removed?', choices: ['the seats', 'historical elements of the facade', 'the roof', 'the parking'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What alternative did he propose?', choices: ['canceling the project', 'keeping the facade and cutting costs elsewhere', 'moving the theater', 'hiring more engineers'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['An engineer facing an ethical dilemma between history and profit', 'A love story', 'A city election', 'A construction accident'], correctIndex: 0 },
    ],
  },
  {
    id: 'db2-brayat-ma-tsifta2atch',
    title: 'Brayat matsayfta2tch',
    translatedTitle: 'Letters that were never sent',
    level: 'B2',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Family reconciliation',
    summary: "A father and son heal an old wound before it's too late.",
    paragraphs: [
      'Lmodda snin, Hassan kan kayhtafed fderj bkoll lbrayat lli kteb lbaba dyalo, lli makanch kayhder m3ah mn ba3d khsam hatta houma jouj maykaytfekroh mezyan.',
      'Koll 3am fdikra khsam, Hassan kan kayketb briya jdida yshrah fiha lli hass bih, walakin 3omro malqach shja3a bash ysayftha.',
      'Mli mrad baba dyalo bshedda, Hassan fhem belli lwaqt lli bqa lih bash ysale7o kan ghadi yqser btariqa matarj3ch.',
      'Qerrar yzor baba fssbitar, w jab m3ah derj kamel dyal lbrayat lli matsayfta2tch, mosta3ed flakhir yeqrahom bsawt 3ali.',
      'Baba sma3 koll kelma bssamt, w domou3 f3aynih, w flakhir ghir qal belli kan tmenna y3ref mn qbel shhal yhemmo lih weldo.',
      'Hadak l3achiya fssbitar, jouj fahmo belli shi jrouh matbrach illa mli shi wahed kayejro2 yeksr ssamt, mahma tal lwaqt.',
    ],
    glossary: [
      { term: 'khsam', translation: 'falling out / conflict' },
      { term: 'shja3a', translation: 'the courage' },
      { term: 'ysale7o', translation: 'to reconcile with him' },
      { term: 'sbitar', translation: 'the hospital' },
      { term: 'domou3', translation: 'the tears' },
      { term: 'jrouh', translation: 'the wounds' },
      { term: 'yejro2', translation: 'dares' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'khsam' mean?", choices: ['falling out / conflict', 'celebration', 'wedding', 'journey'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'jrouh' mean?", choices: ['wounds', 'memories', 'promises', 'letters'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: "Why hadn't Hassan and his father spoken?", choices: ['his father moved abroad', 'a conflict neither remembered well', 'a money dispute', 'disapproval of his job'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What made Hassan finally act?', choices: ["his father's birthday", 'his father becoming seriously ill', "a letter from his mother", "a friend's advice"], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What did Hassan bring to the hospital?', choices: ['flowers', 'a drawer full of unsent letters', 'a photo album', 'medication'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ["A father and son healing an old wound before it's too late", 'A mystery about missing letters', "A hospital's routine", 'Moving to a new city'], correctIndex: 0 },
    ],
  },
  {
    id: 'db2-qarar-lbaqa2',
    title: 'Qrar lbaqa2',
    translatedTitle: 'The decision to stay',
    level: 'B2',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Career & community',
    summary: 'A veterinarian chooses community impact over a lucrative job abroad.',
    paragraphs: [
      'Mli 3rdo 3liha blasa flkharej b2ojra ahsen bezzaf, Khadija tsawrat ghadi teqbel mn ghir ma tfaker bezzaf. Walakin shi haja weqqfatha.',
      'Kant mdda 3achr snin katbni 3iyada baytariya sghira flblda dyalha, blasa makantch fiha had khedma mn qbel.',
      'Lhorafa2 dyalha makanouch ghir lhaywanat: kano ayssan 3a2ilat lli kano m3temdin 3liha, nas wathqin fiha mli kano mohtajin hed y3tani blhaywanat dyalhom.',
      'Khadija qdat asabi3 katfaker flqrar, wa3iya belli lflous ghadi t3awenha t3awen kter l3a2ilatha, walakin ayssan belli ghadi tkhalli faragh s3ib yet3amer flblda.',
      'Flakhir, tkellmat m3a ostad qdim dyalha lli fekkraha belli njah maykaytqasch dima blarqam, walakin blather lli kaykhalli wahed f7ayat nas.',
      'Khadija rfdat l3ard, w 3iwadtou qerrat tewss3 3iyada dyalha btawdif tbib baytari shab, w dmenat hakadha mostaqbal khedma lli t3bat bash tebniha.',
    ],
    glossary: [
      { term: 'ojra', translation: 'salary' },
      { term: '3iyada baytariya', translation: 'veterinary clinic' },
      { term: 'lhorafa2', translation: 'the clients / customers' },
      { term: 'faragh', translation: 'void / emptiness' },
      { term: 'ostad', translation: 'mentor / teacher' },
      { term: 'njah', translation: 'success' },
      { term: 'tewss3', translation: 'expands' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'faragh' mean?", choices: ['void / emptiness', 'opportunity', 'salary', 'celebration'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'tewss3' mean?", choices: ['expands', 'closes', 'sells', 'moves'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What was Khadija offered?', choices: ['a scholarship abroad', 'a better-paying job abroad', 'a bigger house', 'an award'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What has she built over ten years?', choices: ['a restaurant', 'a veterinary clinic', 'a school', 'a farm'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What did her mentor remind her?', choices: ['money is the only measure of success', 'success is measured by impact not numbers', 'she should take the job', 'she should retire'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A veterinarian choosing community impact over a job abroad', 'Training a new pet', 'A financial crisis', 'A romance'], correctIndex: 0 },
    ],
  },
  {
    id: 'db2-rjou3-mn-lghorba',
    title: 'Rjou3 mn lghorba',
    translatedTitle: 'The return from emigration',
    level: 'B2',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Migration & identity',
    summary: 'A man discovers that returning home means embracing change, not the past.',
    paragraphs: [
      'Mn ba3d 3achrin 3am fBelgika, qerrar Abderrahim yerja3 lMaghrib bash y3ich qeddam ma tbqa mn 3omro flblasa lli twlled fiha.',
      'Houma lli tfekkerha ftfoulto tbeddlat bezzaf: bnayat jdad, mahallat jdad, w hatta wjouh jdad maykaytarfhach.',
      'F awel asabi3, hess bghorba akbar mn lli hess biha mli hajer lOroba, w bda yetsawel wach qrar dyalo kan sahih.',
      'Shwiya bshwiya, lqa rasso kayt3araf 3la nas jdad, w kay3awed yektshef ladwaq w rraweh lli nsahom mn zman.',
      "Bent ljiran qdam, lli kebrat daba w wllat mo3allima, hkat lih 3la blasa btariqa 3rfato yshoufha b3in jdida.",
      'Abderrahim fhem belli rjou3 makanch rjou3 lmadi, walakin bidaya jdida fiha lfahm belli blasa katbeddel, b7al nas lli 3aychin fiha.',
    ],
    glossary: [
      { term: 'yetsawel', translation: 'wonders' },
      { term: 'ladwaq', translation: 'the tastes' },
      { term: 'rraweh', translation: 'the smells' },
      { term: 'mo3allima', translation: 'a teacher' },
      { term: 'lmadi', translation: 'the past' },
      { term: 'ghorba', translation: 'alienation / feeling foreign' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'yetsawel' mean?", choices: ['wonders', 'forgets', 'sleeps', 'travels'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'lmadi' mean?", choices: ['the past', 'the future', 'the present', 'the family'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'How long was Abderrahim abroad?', choices: ['10 years', '15 years', '20 years', '30 years'], correctIndex: 2 },
      { id: 'q4', type: 'comprehension', prompt: 'What did he feel in the first weeks back?', choices: ['pure joy', 'a deeper sense of alienation than abroad', 'anger', 'boredom'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'Who helped him see the place with new eyes?', choices: ['his brother', "the neighbor's daughter who became a teacher", 'a stranger', 'his old boss'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A man discovering that returning home means embracing change, not the past', 'A business trip', 'A wedding', 'A mystery'], correctIndex: 0 },
    ],
  },
  {
    id: 'db2-lma-dyal-douar',
    title: "Lma dyal douar",
    translatedTitle: "The village's water",
    level: 'B2',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Community & change',
    summary: 'A village solves a water crisis through cooperation between locals and the diaspora.',
    paragraphs: [
      'Douar Oulad Ya7ya kan kay3temed lsnin twila 3la bir wahed kay3ti lma lkoll 3a2ilat.',
      'Mli bda bir yjeff fsayfiyat, shiyoukh dyal douar tjam3o bash yfekro fhal qbel ma ts3ab l7ala kter.',
      'B3d chabab eqtre7o ydiro qanat jdida mn wad qrib, walakin had hal kan mohtaj flous makantch 3end douar.',
      'Zineb, bent douar lli darat flmdina, sem3at blmoshkil w qerrat t3awen fjem3 flous mn nas lli hajro lkharej.',
      'Bfadl t3awon bin chabab w shiyoukh w ahl douar lli flmohajar, qanat tebnat f aqel mn 3am.',
      'Mn hadak nhar, douar 3awed lqa lma lli mehtajo, w t3allem dars mohim: moshakil kbira katt7all bt3awon machi bwahda.',
    ],
    glossary: [
      { term: 'douar', translation: 'the village' },
      { term: 'bir', translation: 'well' },
      { term: 'yjeff', translation: 'dries up' },
      { term: 'shiyoukh', translation: 'the elders' },
      { term: 'qanat', translation: 'a channel / canal' },
      { term: 'lmohajar', translation: 'the diaspora' },
      { term: 't3awon', translation: 'cooperation' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'bir' mean?", choices: ['well', 'river', 'lake', 'sea'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 't3awon' mean?", choices: ['cooperation', 'competition', 'argument', 'silence'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What problem did the village face?', choices: ['a flood', 'the well drying up in summer', 'a fire', 'a disease'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What did the youth propose?', choices: ['digging a new well', 'building a canal from a nearby river', 'moving the village', 'buying water trucks'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'Who helped raise the money?', choices: ['the mayor', 'Zineb, who reached out to those living abroad', 'a bank', 'a foreign company'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A village solving a water crisis through cooperation between locals and the diaspora', 'A love story', 'A business deal', 'A mystery'], correctIndex: 0 },
    ],
  },

  /* --------------------------------- C1 --------------------------------- */
  {
    id: 'dc1-lkonach-dyal-jed',
    title: 'Lkonach dyal jed',
    translatedTitle: "Grandfather's notebook",
    level: 'C1',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Legacy & family',
    summary: "A woman honors a childhood promise by completing her grandfather's unfinished notebook.",
    paragraphs: [
      'Mnadhu sghorha, kant Nour 3arfa belli jedha trek konach mlyan bqsas w ach3ar makemmelhach qbel ma ytwaffa.',
      'B3d 3oqoud, w hiya daba moharrira ma3rofa, lqat wost hwayjo konach sfer, mlyan bmola7adhat blqlem w mashtoubat.',
      'Flbidaya, trddedat wach 3andha lhaq tatdakhel f3amal machi dyalha, raghm an w3d dyal tfoulatha kan mazal yren fdakiratha ksada makaybench ghadi yhda.',
      'Ghamrat rasha, m3a dalik, fqraya dqiqa lkoll fasl, mhawla tefhem sawt rrwa2i lli jedha bna m3a snin.',
      'Shwiya bshwiya, fahmat belli ikmal konach makanch ma3nah tefred oslob dyalha hiya, walakin te7trem b2amana niya asliya dyal katb.',
      'B3d chhor dyal khedma mt2annia, Nour nashrat konach bismha hiya w ism jedha, wa3iya belli kemmlat flakhir w3d kan akbar mn lklam.',
      'Fhafl taqdim ktab, e3trfat qeddam jomhour belli kitaba hadak nihaya makanetch fi3l ib3da3, walakin fi3l isgha3 3amiq w sabour.',
    ],
    glossary: [
      { term: 'konach', translation: 'the notebook' },
      { term: 'mashtoubat', translation: 'crossed-out marks' },
      { term: 'sada', translation: 'an echo' },
      { term: 'ghamrat rasha', translation: 'immersed herself' },
      { term: 'sawt rrwa2i', translation: 'the narrative voice' },
      { term: 'niya asliya', translation: 'the original intention' },
      { term: "mt2annia", translation: 'meticulous / careful' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'konach' mean?", choices: ['notebook', 'letter', 'photo album', 'diary entry'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'sada' mean?", choices: ['echo', 'silence', 'promise', 'memory'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What had Nour promised as a child?', choices: ['to become a writer', "to finish her grandfather's unfinished notebook", 'to travel', 'to publish her own memoir'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: "What did Nour find among his belongings?", choices: ['a diary', 'a yellowed notebook full of notes', 'letters', 'a typewriter'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What did she realize while working on it?', choices: ['she should rewrite it in her own style', 'she needed to honor his original intention', "it wasn't worth finishing", 'she should hire someone'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ["A woman honoring a childhood promise by completing her grandfather's unfinished notebook", 'A mystery about a stolen manuscript', 'A publishing rivalry', 'Learning to write'], correctIndex: 0 },
    ],
  },
  {
    id: 'dc1-taman-skoat',
    title: 'Taman skout',
    translatedTitle: 'The price of silence',
    level: 'C1',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Integrity & journalism',
    summary: 'A journalist risks her career to expose the truth about a corrupt public project.',
    paragraphs: [
      'Fjarida dyal mdina, kolshi kan 3aref belli Sanaa hiya sa7afiya lakthar israr, qadra tekshef qssas nas okhrin kano mfaddlin ykhalliwha madfouna.',
      'Mli wslha khbar mjhoul lmasdar 3la mokhalafat fbina2 qentra 3oumoumiya, fahmat belli had ta7qiq momken ykellefha khedma dyalha.',
      'Modir jarida, taht daght masali7 siyassiya, nabbahha btariqa ghir mobachira belli nashr maqal ghadi yjib 3awaqib s3ib yattwaqqa3ouha.',
      'Sanaa qdat lyali kamla katakked mn koll ma3louma, wa3iya belli ghelta wahda sghira kafiya bash tkhalli koll ta7qiq w sam3atha fshek.',
      'Raghm dghout, qerrat belli skout ghadi yawzen kter 3la dmir dyalha mn ay 3iqab mihani momken t3ani mno 3la qol lha9iqa.',
      'Nhar lli nchar fih maqal, bezzaf dyal lmas2oulin t3azlo, w ta7qiq rasmi tfeth 3la bina2 qentra.',
      'B3d chhor, hatta ila khesrat blasetha fjarida, Sanaa qeblat belli khellsat taman 3adel mqabel makhanetch shi kant momina bih.',
    ],
    glossary: [
      { term: 'israr', translation: 'persistence' },
      { term: 'mokhalafat', translation: 'violations / irregularities' },
      { term: 'ta7qiq', translation: 'investigation' },
      { term: 'mas2oulin', translation: 'the officials' },
      { term: 't3azlo', translation: 'were removed' },
      { term: 'dmir', translation: 'the conscience' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'israr' mean?", choices: ['persistence', 'carelessness', 'timidity', 'forgetfulness'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'dmir' mean?", choices: ['conscience', 'reward', 'promotion', 'apology'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What did Sanaa investigate?', choices: ['a hospital scandal', "irregularities in a public bridge's construction", 'a bank fraud', 'an election scandal'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What did the newspaper director do?', choices: ['encouraged immediate publishing', 'subtly warned her of consequences', 'fired her instantly', 'offered a promotion'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What happened after publishing?', choices: ['nothing changed', 'several officials were removed and an investigation opened', 'she was promoted', 'the paper closed'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A journalist risking her career to expose the truth about a corrupt public project', 'A newsroom romance', 'A political campaign', 'Building a bridge'], correctIndex: 0 },
    ],
  },
  {
    id: 'dc1-khariita-bla-ism',
    title: 'Kharita bla ism',
    translatedTitle: 'A map without a name',
    level: 'C1',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Discovery & memory',
    summary: "A man uncovers his great-aunt's secret documentation of a forgotten settlement.",
    paragraphs: [
      'Mn bin hwayej lli wrethha mn khalto lkbira, lqa Ilyas kharita qdima, marssouma bilyad, bla ay ichara 3la blasa wla tarikh.',
      'Maftoun bhad lektichaf, qerrar yastachir khabir khara2it mtqa3ed lli, b3d ma fahas warqa sfra, t3arraf 3la b3d lmalamih dyal mantiqa jabaliya b3ida.',
      'Madfou3 bfoudoul qrib mn hawass, Ilyas nadhem rehla estikchaf bash yatakked wach kharita katwafeq m3a blasa haqiqiya aw kant ghir mn khayal khalto.',
      'B3d ayyam dyal mchi fdorob blkad ma3roufa, fariq wsel lwad mkhabi kan ywafeq btariqa modh-hila m3a khottot dyal kharita asliya.',
      'Tema, ektshfo atlal douar sghir, yban mahjour mnadhu 3oqoud, makansh 3lih ay tasjil rasmi.',
      "Ilyas fhem 3endi'dh belli khalto lkbira makanetch rasmat blasa khayaliya, walakin wettqat bssir roken mn l3alam lli zman hkem 3lih bnnisyan.",
      'Mli rja3, nashr lektichafat dyalo fmajala tarikh mahalliya, raje3 bhad tariqa, btariqa ma, ism ddaye3 lhad blasa mansiya.',
    ],
    glossary: [
      { term: 'maftoun', translation: 'fascinated' },
      { term: 'khabir khara2it', translation: 'a cartographer' },
      { term: 'hawass', translation: 'obsession' },
      { term: 'dorob', translation: 'paths / trails' },
      { term: 'atlal', translation: 'ruins' },
      { term: 'mahjour', translation: 'abandoned' },
      { term: 'nnisyan', translation: 'oblivion / forgetting' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'mahjour' mean?", choices: ['abandoned', 'new', 'famous', 'hidden treasure'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'nnisyan' mean?", choices: ['oblivion / forgetting', 'celebration', 'danger', 'treasure'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'Who did Ilyas consult about the map?', choices: ['a historian', 'a retired cartographer', 'a park ranger', 'his great-aunt'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What did they find in the hidden valley?', choices: ['a treasure chest', 'the ruins of an abandoned settlement', 'a new animal species', 'a modern town'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'How did Ilyas conclude the story?', choices: ['he sold the map', 'he published his findings in a local history magazine', 'he kept it secret', 'he moved there'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ["A man uncovering his great-aunt's secret documentation of a forgotten settlement", 'A gold treasure hunt', 'Learning cartography', 'A land conflict'], correctIndex: 0 },
    ],
  },
  {
    id: 'dc1-bin-dafatin',
    title: 'Bin dafftin',
    translatedTitle: 'Between two shores',
    level: 'C1',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Migration & identity',
    summary: 'A man embraces a dual identity as a bridge rather than a division.',
    paragraphs: [
      'Karim twlled fMarrakech w tra3ra3 fMarseille, 3aych da2iman bin lloghtayn, thaqafatayn, w hess blentima2 lli makansh dima wadeh.',
      "Flmadrasa fransawiya, kan yhess belli shi haja fih ghriba 3la lakhrin, w fsayfiyat flMaghrib, b3d qraybo kano kayshoufouh b7al 'Roumi sghir'.",
      'M3a lwaqt, bdel ma yakhtar bin hawiyato, Karim bda yefhem belli tanaqod lli hass bih kayqder ykoun ghna blasa ma ykoun tqel.',
      'Qerrar yekteb modhakkarat 3an tfoulto, machi bash yhel hawiyato nnihaiya, walakin bash ywattaq tajriba m3aqqada dyal koll wahed 3aych bin dafftin.',
      'Mli nachar ktab, wslouh rasa2il mn nas 3aychin nfs tajriba, lli hesso lmarra lawla belli shi wahed fhem bddabt lli kano hassin bih.',
      'Karim fhem 3endi\'dh belli hawiya machi da2iman ikhtiyar wahed, walakin momken tkoun jesr bin 3awalim mota3addida, ila qeblha wahed bla khejel.',
      'Daba, Karim kayqol bfakhr belli howa maghribi w fransawi fnfs lwaqt, bla haja ybarrer had t3addod lehed.',
    ],
    glossary: [
      { term: 'tra3ra3', translation: 'grew up' },
      { term: 'lentima2', translation: 'belonging' },
      { term: 'tanaqod', translation: 'the contradiction' },
      { term: 'modhakkarat', translation: 'memoirs' },
      { term: 'jesr', translation: 'a bridge' },
      { term: "t3addod", translation: 'the multiplicity' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'jesr' mean?", choices: ['bridge', 'wall', 'road', 'border'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'lentima2' mean?", choices: ['belonging', 'poverty', 'confusion', 'silence'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'Where did Karim grow up?', choices: ['Marrakech', 'Marseille', 'Casablanca', 'Paris'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'Why did he write his memoir?', choices: ['to resolve his identity once and for all', 'to document the complex experience of living between two shores', 'for money', 'to please his family'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What happened after he published the book?', choices: ['nothing', 'people with the same experience wrote to him', 'he was criticized', 'he moved back to Morocco'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A man embracing a dual identity as a bridge rather than a division', 'A love story', 'A business trip', 'A cooking memoir'], correctIndex: 0 },
    ],
  },
  {
    id: 'dc1-lmosalaha',
    title: 'Lmssale7a',
    translatedTitle: 'The reconciliation',
    level: 'C1',
    language: 'Moroccan Darija',
    nativeLanguage: 'English',
    topic: 'Forgiveness & family',
    summary: "Two brothers heal a long rift after their mother's final wish.",
    paragraphs: [
      'Lmodda khemstach 3am, lekhwan Rachid w Karim makanouch kayhedro, mn ba3d niza3 3la irt baba dyalhom lli trek jrouh 3amiqa f3a2ila kamla.',
      'Koll wahed fihom bna haya monfasila, walakin ghiyab dyal akhor kan hader btariqa samta fkoll monasaba 3a2iliya, fkoll 3id w 3ers.',
      'Mli mardat lwalida, jouj tlaqaw la2wel marra fssbitar, ghir anna lklam binhom kant mazalt mothaqqala blmadi.',
      'Lwalida, wa3iya belli lwaqt dyalha kayqser, tlebat mnhom w3d akhir: yhawlo ysale7o qbel ma tkoun fawat lawan.',
      'B3d wafatha, Rachid w Karim ejtama3o la2wel marra bla hodour hed akhor, w tkellmo, la2wel marra mnadhu snin, 3la lli kano hassin bih f3lan.',
      'Fahmo belli niza3 3la mal makanch abadan sabab l7aqiqi, walakin ghir ghita2 ljrouh aqdam makanouch qadrin y3abbro 3liha.',
      'Lyoum, Rachid w Karim kaytlaqaw koll yom jem3a 3la qahwa, moqtan3in belli b3d jrouh katbra ghir mli shakhs kayqbel yeksr ssamt, mahma tal zman.',
    ],
    glossary: [
      { term: 'niza3', translation: 'dispute / conflict' },
      { term: 'irt', translation: 'inheritance' },
      { term: 'jrouh 3amiqa', translation: 'deep wounds' },
      { term: 'mothaqqala', translation: 'burdened' },
      { term: 'fawat lawan', translation: 'too late' },
      { term: 'ghita2', translation: 'a cover / facade' },
      { term: 'ssamt', translation: 'the silence' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'irt' mean?", choices: ['inheritance', 'gift', 'salary', 'debt'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'ghita2' mean?", choices: ['cover / facade', 'solution', 'wound', 'promise'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: "Why hadn't Rachid and Karim spoken for 15 years?", choices: ['a business rivalry', "a dispute over their father's inheritance", 'a political disagreement', 'they lived in different countries'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What did the mother ask of them?', choices: ['to sell the family house', "to reconcile before it's too late", 'to move closer to her', 'to forgive their father'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What did they realize the true cause of their conflict was?', choices: ['it really was about the money', 'the money was a cover for older, unexpressed wounds', 'there was no real conflict', 'their father caused it deliberately'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ["Two brothers healing a long rift after their mother's final wish", 'A business dispute resolved in court', 'A story about inheritance law', 'A wedding celebration'], correctIndex: 0 },
    ],
  },
];
