/**
 * Built-in reading library: short Spanish stories from A1 to C1, each with a
 * glossary of key vocabulary and a post-reading quiz covering vocabulary,
 * comprehension and subject/theme.
 */

import type { RawStory } from './storyUtils';

export const SPANISH_RAW_STORIES: RawStory[] = [
  /* --------------------------------- A1 --------------------------------- */
  {
    id: 'a1-un-dia-en-la-vida-de-ana',
    title: 'Un día en la vida de Ana',
    translatedTitle: "A day in Ana's life",
    level: 'A1',
    language: 'Spanish',
    nativeLanguage: 'English',
    topic: 'Daily routine',
    summary: 'Ana walks us through a typical day, from breakfast to dinner with her family.',
    paragraphs: [
      'Ana vive en Madrid. Ella es estudiante y tiene veinte años. Todos los días, Ana se levanta a las siete de la mañana.',
      'Primero, Ana desayuna pan con mantequilla y bebe un café con leche. Después, ella se ducha y se viste rápido.',
      'Ana va a la universidad en autobús. El autobús es azul y siempre llega a las ocho y media.',
      'Por la tarde, Ana estudia en la biblioteca con sus amigos. Ellos hablan español y también un poco de inglés.',
      'Por la noche, Ana cena con su familia. Su madre cocina arroz con pollo. ¡A Ana le encanta la comida de su madre!',
    ],
    glossary: [
      { term: 'se levanta', translation: 'gets up' },
      { term: 'desayuna', translation: 'has breakfast' },
      { term: 'mantequilla', translation: 'butter' },
      { term: 'se ducha', translation: 'showers' },
      { term: 'se viste', translation: 'gets dressed' },
      { term: 'autobús', translation: 'bus' },
      { term: 'biblioteca', translation: 'library' },
      { term: 'amigos', translation: 'friends' },
      { term: 'cena', translation: 'has dinner / dinner' },
      { term: 'le encanta', translation: 'she loves it' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'se levanta' mean?", choices: ['gets up', 'goes to sleep', 'eats lunch', 'takes a shower'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'biblioteca' mean?", choices: ['library', 'bakery', 'hospital', 'school'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What time does Ana get up?', choices: ['6:00', '7:00', '7:30', '8:30'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'How does Ana get to the university?', choices: ['by car', 'by bus', 'walking', 'by bike'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'Who cooks dinner in the story?', choices: ['Ana', "Ana's mother", "Ana's friend", "Ana's father"], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A trip to another city', "Ana's daily routine", 'A birthday party', 'A cooking competition'], correctIndex: 1 },
    ],
  },
  {
    id: 'a1-la-familia-de-carlos',
    title: 'La familia de Carlos',
    translatedTitle: "Carlos's family",
    level: 'A1',
    language: 'Spanish',
    nativeLanguage: 'English',
    topic: 'Family',
    summary: 'Carlos introduces his big family and their favorite weekend tradition.',
    paragraphs: [
      'Carlos tiene una familia grande. Él tiene dos hermanos y una hermana. Sus padres se llaman Pedro y Rosa.',
      'El hermano mayor de Carlos se llama Luis. Luis tiene treinta años y trabaja en un banco.',
      'La hermana de Carlos se llama Sofía. Sofía es muy simpática y estudia medicina en la universidad.',
      'Los fines de semana, toda la familia come junta en casa de los abuelos. La abuela prepara una sopa deliciosa.',
      'A Carlos le gusta jugar al fútbol con su hermano pequeño, Diego. Diego tiene solo ocho años, pero juega muy bien.',
    ],
    glossary: [
      { term: 'hermanos', translation: 'siblings / brothers' },
      { term: 'hermana', translation: 'sister' },
      { term: 'padres', translation: 'parents' },
      { term: 'hermano mayor', translation: 'older brother' },
      { term: 'banco', translation: 'bank' },
      { term: 'simpática', translation: 'nice, friendly' },
      { term: 'medicina', translation: 'medicine' },
      { term: 'abuelos', translation: 'grandparents' },
      { term: 'sopa', translation: 'soup' },
      { term: 'hermano pequeño', translation: 'younger brother' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'hermana' mean?", choices: ['sister', 'mother', 'cousin', 'aunt'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'abuelos' mean?", choices: ['grandparents', 'neighbors', 'teachers', 'parents'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'How many siblings does Carlos have in total?', choices: ['1', '2', '3', '4'], correctIndex: 2 },
      { id: 'q4', type: 'comprehension', prompt: 'What does Sofía study?', choices: ['Law', 'Medicine', 'Engineering', 'Art'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'Who cooks soup on weekends?', choices: ["Carlos's mother", 'the grandmother', 'Sofía', 'Luis'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ["Carlos's job", "Carlos's family", 'A football match', 'A trip to the bank'], correctIndex: 1 },
    ],
  },
  {
    id: 'a1-en-el-mercado',
    title: 'En el mercado',
    translatedTitle: 'At the market',
    level: 'A1',
    language: 'Spanish',
    nativeLanguage: 'English',
    topic: 'Shopping & food',
    summary: "María's Saturday routine of buying fresh food at the local market.",
    paragraphs: [
      'Los sábados, María va al mercado con su cesta. El mercado está cerca de su casa y abre muy temprano.',
      'María compra frutas frescas: manzanas rojas, plátanos amarillos y naranjas dulces. Las frutas no son caras.',
      'También compra verduras: tomates, cebollas y patatas. El vendedor de verduras es muy amable con María.',
      'En el mercado hay una panadería pequeña. María siempre compra pan fresco y, a veces, un pastel de chocolate.',
      'Cuando termina de comprar, María vuelve a casa y prepara el almuerzo para su familia. ¡Todo es muy fresco y rico!',
    ],
    glossary: [
      { term: 'mercado', translation: 'market' },
      { term: 'cesta', translation: 'basket' },
      { term: 'frutas', translation: 'fruits' },
      { term: 'manzanas', translation: 'apples' },
      { term: 'plátanos', translation: 'bananas' },
      { term: 'naranjas', translation: 'oranges' },
      { term: 'verduras', translation: 'vegetables' },
      { term: 'vendedor', translation: 'seller' },
      { term: 'panadería', translation: 'bakery' },
      { term: 'almuerzo', translation: 'lunch' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'cesta' mean?", choices: ['basket', 'box', 'bag', 'cart'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'panadería' mean?", choices: ['bakery', 'pharmacy', 'butcher shop', 'market'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What day does María go to the market?', choices: ['Friday', 'Saturday', 'Sunday', 'Monday'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What does María buy at the bakery besides bread?', choices: ['a cake', 'cookies', 'a sandwich', 'ice cream'], correctIndex: 0 },
      { id: 'q5', type: 'comprehension', prompt: 'How does the vegetable seller treat María?', choices: ['rudely', 'indifferently', 'kindly', 'impatiently'], correctIndex: 2 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A trip to the doctor', 'A Saturday shopping trip at the market', 'Cooking a birthday cake', 'A family vacation'], correctIndex: 1 },
    ],
  },

  /* --------------------------------- A2 --------------------------------- */
  {
    id: 'a2-un-fin-de-semana-en-la-playa',
    title: 'Un fin de semana en la playa',
    translatedTitle: 'A weekend at the beach',
    level: 'A2',
    language: 'Spanish',
    nativeLanguage: 'English',
    topic: 'Travel',
    summary: 'Laura and her friends spend an unforgettable weekend at a coastal town.',
    paragraphs: [
      'El verano pasado, Laura y sus amigos decidieron pasar el fin de semana en la playa. Salieron de la ciudad el viernes por la tarde.',
      'Llegaron a un pequeño pueblo costero donde alquilaron una casa cerca del mar. La casa tenía una vista hermosa.',
      'El sábado por la mañana, todos nadaron en el mar y jugaron al vóley playa. El agua estaba fría, pero muy limpia.',
      'Por la tarde, comieron pescado fresco en un restaurante junto a la playa. Laura pidió paella y le encantó.',
      'Por la noche, hicieron una fogata en la arena y cantaron canciones hasta muy tarde. Fue un fin de semana inolvidable.',
      'El domingo, antes de volver a casa, caminaron por la orilla y recogieron conchas como recuerdo del viaje.',
    ],
    glossary: [
      { term: 'alquilaron', translation: 'they rented' },
      { term: 'costero', translation: 'coastal' },
      { term: 'nadaron', translation: 'they swam' },
      { term: 'fogata', translation: 'bonfire' },
      { term: 'arena', translation: 'sand' },
      { term: 'orilla', translation: 'shore' },
      { term: 'conchas', translation: 'shells' },
      { term: 'inolvidable', translation: 'unforgettable' },
      { term: 'pidió', translation: 'ordered / asked for' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'alquilaron' mean?", choices: ['rented', 'bought', 'sold', 'built'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'fogata' mean?", choices: ['bonfire', 'boat', 'tent', 'storm'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'When did they leave the city?', choices: ['Thursday morning', 'Friday afternoon', 'Saturday night', 'Sunday morning'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What did Laura order at the restaurant?', choices: ['fish soup', 'paella', 'salad', 'tacos'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What did they do on Sunday before leaving?', choices: ['went swimming', 'played volleyball', 'walked the shore and collected shells', 'cooked paella'], correctIndex: 2 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A business trip', 'A memorable weekend at the beach with friends', 'A fishing competition', 'Moving to a new house'], correctIndex: 1 },
    ],
  },
  {
    id: 'a2-el-cumpleanos-sorpresa',
    title: 'El cumpleaños sorpresa',
    translatedTitle: 'The surprise birthday',
    level: 'A2',
    language: 'Spanish',
    nativeLanguage: 'English',
    topic: 'Friendship & celebrations',
    summary: "Marta's friends secretly plan a surprise party for her birthday.",
    paragraphs: [
      'Era el cumpleaños de Marta y sus amigos querían organizarle una fiesta sorpresa. Nadie le dijo nada a Marta.',
      'Pablo compró globos y decoraciones de colores. Ana preparó una tarta enorme de chocolate y fresas.',
      'El día de la fiesta, los amigos se escondieron en la sala antes de que Marta llegara del trabajo.',
      'Cuando Marta abrió la puerta, todos gritaron "¡Sorpresa!" y ella se puso muy contenta. Casi lloró de emoción.',
      'Bailaron toda la noche y comieron la tarta de chocolate. Marta dijo que fue el mejor cumpleaños de su vida.',
      'Al final de la fiesta, Marta agradeció a todos sus amigos por el esfuerzo y el cariño que le mostraron.',
    ],
    glossary: [
      { term: 'sorpresa', translation: 'surprise' },
      { term: 'globos', translation: 'balloons' },
      { term: 'decoraciones', translation: 'decorations' },
      { term: 'tarta', translation: 'cake' },
      { term: 'se escondieron', translation: 'they hid' },
      { term: 'gritaron', translation: 'they shouted' },
      { term: 'se puso muy contenta', translation: 'she became very happy' },
      { term: 'lloró', translation: 'cried' },
      { term: 'agradeció', translation: 'thanked' },
      { term: 'esfuerzo', translation: 'effort' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'globos' mean?", choices: ['balloons', 'flowers', 'candles', 'gifts'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'se escondieron' mean?", choices: ['they hid', 'they danced', 'they left', 'they cooked'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'Who prepared the cake?', choices: ['Marta', 'Pablo', 'Ana', "Marta's mother"], correctIndex: 2 },
      { id: 'q4', type: 'comprehension', prompt: 'What flavor was the cake?', choices: ['vanilla', 'chocolate and strawberries', 'lemon', 'caramel'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'How did Marta react when she saw the surprise?', choices: ['she got angry', 'she was confused', 'she got very happy and almost cried', 'she left the room'], correctIndex: 2 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A cooking class', 'A surprise birthday party organized by friends', 'A work meeting', 'A trip abroad'], correctIndex: 1 },
    ],
  },
  {
    id: 'a2-un-viaje-en-tren',
    title: 'Un viaje en tren',
    translatedTitle: 'A train journey',
    level: 'A2',
    language: 'Spanish',
    nativeLanguage: 'English',
    topic: 'Travel',
    summary: "Diego takes a relaxing train trip to Barcelona for work.",
    paragraphs: [
      'Diego tenía que viajar a Barcelona por trabajo. Decidió tomar el tren porque le gustaba ver el paisaje por la ventana.',
      'Compró su billete por internet la noche anterior y llegó a la estación con tiempo de sobra.',
      'En el tren, Diego se sentó junto a una señora mayor que leía un libro de misterio. Hablaron un poco durante el viaje.',
      'El tren paró en varias estaciones pequeñas. En una de ellas, subió un grupo de estudiantes muy ruidosos.',
      'Después de tres horas de viaje, Diego llegó a Barcelona cansado pero contento. Tomó un taxi hasta su hotel.',
      'Esa noche, cenó en un restaurante cerca del mar y pensó que el viaje en tren había sido muy tranquilo y agradable.',
    ],
    glossary: [
      { term: 'billete', translation: 'ticket' },
      { term: 'estación', translation: 'station' },
      { term: 'señora mayor', translation: 'elderly lady' },
      { term: 'misterio', translation: 'mystery' },
      { term: 'ruidosos', translation: 'noisy' },
      { term: 'cansado', translation: 'tired' },
      { term: 'agradable', translation: 'pleasant' },
      { term: 'paisaje', translation: 'landscape' },
      { term: 'viaje', translation: 'trip' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'billete' mean?", choices: ['ticket', 'suitcase', 'passport', 'map'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'ruidosos' mean?", choices: ['noisy', 'quiet', 'tired', 'happy'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'Why did Diego choose the train?', choices: ['it was cheaper', 'he liked seeing the landscape', 'it was faster', 'his car broke down'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'Who did Diego sit next to?', choices: ['a group of students', 'an elderly lady reading a mystery book', 'his boss', 'a child'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'How long was the journey?', choices: ['one hour', 'two hours', 'three hours', 'five hours'], correctIndex: 2 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A business trip to Barcelona by train', 'A camping adventure', 'A family reunion', 'A cooking trip'], correctIndex: 0 },
    ],
  },

  /* --------------------------------- B1 --------------------------------- */
  {
    id: 'b1-el-nuevo-trabajo-de-marta',
    title: 'El nuevo trabajo de Marta',
    translatedTitle: "Marta's new job",
    level: 'B1',
    language: 'Spanish',
    nativeLanguage: 'English',
    topic: 'Work & belonging',
    summary: 'Marta overcomes her nerves and finds her place on a new team.',
    paragraphs: [
      'Después de buscar empleo durante meses, Marta finalmente consiguió un puesto en una empresa de tecnología. Estaba muy nerviosa por su primer día.',
      'Aunque tenía experiencia como diseñadora, nunca había trabajado en un equipo tan grande. Le preocupaba no encajar con sus nuevos compañeros.',
      'El primer día, su jefe le presentó al equipo y le explicó los proyectos en los que trabajarían juntos durante el próximo trimestre.',
      'Con el paso de las semanas, Marta se dio cuenta de que sus compañeros eran muy amables y siempre estaban dispuestos a ayudarla.',
      'Poco a poco, empezó a sentirse parte del equipo. Incluso propuso una idea para mejorar el diseño de la aplicación que la empresa desarrollaba.',
      'Al final del trimestre, su jefe la felicitó públicamente por su trabajo. Marta se sintió orgullosa de haber superado sus miedos iniciales.',
    ],
    glossary: [
      { term: 'empleo', translation: 'employment / job' },
      { term: 'puesto', translation: 'position' },
      { term: 'diseñadora', translation: 'designer' },
      { term: 'equipo', translation: 'team' },
      { term: 'encajar', translation: 'to fit in' },
      { term: 'jefe', translation: 'boss' },
      { term: 'dispuestos', translation: 'willing' },
      { term: 'propuso', translation: 'proposed' },
      { term: 'superado', translation: 'overcome' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'encajar' mean?", choices: ['to fit in', 'to argue', 'to resign', 'to travel'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'dispuestos' mean?", choices: ['willing', 'tired', 'angry', 'confused'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: "What was Marta's profession before the new job?", choices: ['Engineer', 'Designer', 'Accountant', 'Teacher'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What worried Marta the most about the new job?', choices: ['the salary', 'not fitting in with a large team', 'the commute', 'the working hours'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What did Marta propose to the team?', choices: ['a new marketing plan', "an idea to improve the app's design", 'a new hiring process', 'a team trip'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['Marta overcoming her fears while adapting to a new job', 'A company going bankrupt', 'A job interview that failed', 'A team building trip abroad'], correctIndex: 0 },
    ],
  },
  {
    id: 'b1-una-carta-desde-mexico',
    title: 'Una carta desde México',
    translatedTitle: 'A letter from Mexico',
    level: 'B1',
    language: 'Spanish',
    nativeLanguage: 'English',
    topic: 'Friendship & distance',
    summary: 'Elena and Clara keep their friendship alive through letters as Elena builds a new life abroad.',
    paragraphs: [
      'Cuando Elena se mudó a México por su trabajo, prometió a su mejor amiga, Clara, que le escribiría cartas en lugar de solo enviar mensajes.',
      'En su primera carta, Elena describió la Ciudad de México con entusiasmo: los colores de los mercados, el sabor de la comida y la amabilidad de la gente.',
      'Clara respondió contándole las noticias de su ciudad y confesando que extrañaba mucho a su amiga, aunque se alegraba de verla tan feliz.',
      'Con el tiempo, las cartas de Elena empezaron a hablar de un compañero de trabajo, Rodrigo, con quien pasaba cada vez más tiempo.',
      'Clara notó el cambio de tono en las cartas y, entre líneas, adivinó que su amiga se había enamorado, aunque Elena no lo mencionara directamente.',
      'Un año después, Elena escribió una última carta anunciando que se casaría con Rodrigo en la Ciudad de México, y que esperaba que Clara viajara para la boda.',
    ],
    glossary: [
      { term: 'se mudó', translation: 'moved' },
      { term: 'prometió', translation: 'promised' },
      { term: 'entusiasmo', translation: 'enthusiasm' },
      { term: 'amabilidad', translation: 'kindness' },
      { term: 'extrañaba', translation: 'missed (someone)' },
      { term: 'compañero de trabajo', translation: 'coworker' },
      { term: 'adivinó', translation: 'guessed' },
      { term: 'enamorado', translation: 'in love' },
      { term: 'boda', translation: 'wedding' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'extrañaba' mean?", choices: ['missed', 'forgot', 'visited', 'invited'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'boda' mean?", choices: ['wedding', 'birthday', 'graduation', 'funeral'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'Why did Elena move?', choices: ['to study', 'for her job', 'to be with family', 'to retire'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'Who is Rodrigo?', choices: ["Elena's brother", "Elena's coworker", "Clara's husband", "Elena's neighbor"], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'How did Clara find out Elena was in love?', choices: ['Elena told her directly', 'she read it between the lines of the letters', 'Rodrigo told her', 'she visited Mexico'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A friendship kept alive through letters as Elena builds a new life in Mexico', 'A business trip gone wrong', 'A cooking exchange between friends', 'A mystery about a missing letter'], correctIndex: 0 },
    ],
  },
  {
    id: 'b1-el-misterio-del-gato-perdido',
    title: 'El misterio del gato perdido',
    translatedTitle: 'The mystery of the lost cat',
    level: 'B1',
    language: 'Spanish',
    nativeLanguage: 'English',
    topic: 'Mystery',
    summary: 'A woman solves the mystery of her missing cat — and finds a lost ring along the way.',
    paragraphs: [
      'Una mañana, la señora Ibáñez descubrió que su gato, Rayo, había desaparecido. Buscó por toda la casa, pero no encontró ni rastro de él.',
      'Preocupada, decidió preguntar a sus vecinos si lo habían visto. El señor del piso de abajo dijo que había escuchado un maullido durante la noche.',
      'Con esa pista, la señora Ibáñez revisó el sótano del edificio, un lugar oscuro donde nunca antes había entrado.',
      'Allí, entre cajas viejas, encontró a Rayo atrapado detrás de un armario. Parecía que se había quedado encerrado sin querer.',
      'Al rescatarlo, notó que el gato tenía algo brillante en la boca: un pequeño anillo que probablemente pertenecía a otro vecino.',
      'La señora Ibáñez decidió preguntar por el edificio hasta encontrar al dueño del anillo, y así resolvió dos misterios en un solo día.',
    ],
    glossary: [
      { term: 'desaparecido', translation: 'disappeared' },
      { term: 'rastro', translation: 'trace' },
      { term: 'vecinos', translation: 'neighbors' },
      { term: 'maullido', translation: 'meow' },
      { term: 'pista', translation: 'clue' },
      { term: 'sótano', translation: 'basement' },
      { term: 'atrapado', translation: 'trapped' },
      { term: 'encerrado', translation: 'locked in' },
      { term: 'anillo', translation: 'ring' },
      { term: 'dueño', translation: 'owner' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'sótano' mean?", choices: ['basement', 'attic', 'garden', 'rooftop'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'pista' mean?", choices: ['clue', 'key', 'letter', 'photograph'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'Who gave the señora Ibáñez the first clue?', choices: ['a police officer', 'the neighbor from downstairs', 'her sister', 'the building doorman'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'Where was the cat found?', choices: ['on the roof', 'in the basement behind a cabinet', 'in the garden', "at a neighbor's apartment"], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: "What did the cat have in its mouth?", choices: ['a piece of food', 'a small ring', 'a toy', 'a key'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A woman solving the mystery of her missing cat and finding a lost ring', 'A robbery in an apartment building', "A veterinarian's daily routine", 'A story about moving to a new city'], correctIndex: 0 },
    ],
  },

  /* --------------------------------- B2 --------------------------------- */
  {
    id: 'b2-el-dilema-del-arquitecto',
    title: 'El dilema del arquitecto',
    translatedTitle: "The architect's dilemma",
    level: 'B2',
    language: 'Spanish',
    nativeLanguage: 'English',
    topic: 'Ethics & work',
    summary: 'An architect must choose between profit and preserving a historic theater.',
    paragraphs: [
      'Fernando llevaba quince años trabajando como arquitecto en el mismo estudio, diseñando edificios que rara vez veía terminados con sus propios ojos.',
      'Un día, le ofrecieron dirigir un proyecto ambicioso: la restauración de un antiguo teatro que la ciudad quería convertir en un centro cultural.',
      'El problema era que, para que el proyecto fuera rentable, la empresa insistía en que se eliminaran varios elementos históricos de la fachada original.',
      'Fernando sentía que aceptar esas condiciones traicionaría el espíritu del edificio, aunque rechazar el proyecto pusiera en riesgo su puesto en la empresa.',
      'Después de varias noches sin dormir, decidió proponer una alternativa: mantener la fachada intacta y reducir costos en otras áreas menos visibles del edificio.',
      'Para su sorpresa, el ayuntamiento aceptó su propuesta con entusiasmo, y el teatro restaurado se convirtió en el proyecto del que Fernando se sentía más orgulloso.',
    ],
    glossary: [
      { term: 'dilema', translation: 'dilemma' },
      { term: 'rentable', translation: 'profitable' },
      { term: 'fachada', translation: 'facade' },
      { term: 'traicionaría', translation: 'would betray' },
      { term: 'rechazar', translation: 'to reject / refuse' },
      { term: 'riesgo', translation: 'risk' },
      { term: 'propuesta', translation: 'proposal' },
      { term: 'ayuntamiento', translation: 'city hall' },
      { term: 'restauración', translation: 'restoration' },
      { term: 'orgulloso', translation: 'proud' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'fachada' mean?", choices: ['facade', 'foundation', 'roof', 'hallway'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'rentable' mean?", choices: ['profitable', 'historic', 'dangerous', 'modern'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What project was Fernando offered?', choices: ['building a new stadium', 'restoring an old theater', 'designing a shopping mall', 'renovating his own house'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What did the company want to remove?', choices: ["the theater's seats", 'historical elements of the facade', 'the roof', 'the parking lot'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What alternative did Fernando propose?', choices: ['canceling the project', 'keeping the facade and cutting costs elsewhere', 'moving the theater', 'hiring more architects'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['An architect facing an ethical dilemma about preserving history versus profit', 'A love story between two architects', 'A city hall election', 'A construction accident'], correctIndex: 0 },
    ],
  },
  {
    id: 'b2-cartas-que-nunca-se-enviaron',
    title: 'Cartas que nunca se enviaron',
    translatedTitle: 'Letters that were never sent',
    level: 'B2',
    language: 'Spanish',
    nativeLanguage: 'English',
    topic: 'Family reconciliation',
    summary: 'A father and son heal an old wound before it is too late.',
    paragraphs: [
      'Durante años, Ricardo guardó en un cajón todas las cartas que había escrito para su padre, con quien no hablaba desde una discusión que ninguno de los dos recordaba bien.',
      'Cada aniversario de la pelea, Ricardo escribía una nueva carta explicando lo que sentía, pero nunca reunía el valor suficiente para enviarla.',
      'Cuando su padre enfermó gravemente, Ricardo comprendió que el tiempo que le quedaba para reconciliarse se acortaba de manera irreversible.',
      'Decidió entonces visitarlo en el hospital, llevando consigo el cajón entero de cartas sin enviar, dispuesto por fin a leerlas en voz alta.',
      'Su padre escuchó cada palabra en silencio, con lágrimas en los ojos, y al final simplemente dijo que ojalá hubiera sabido antes cuánto le importaba a su hijo.',
      'Aquella tarde en el hospital, ambos comprendieron que algunas heridas solo sanan cuando alguien se atreve a romper el silencio, sin importar cuánto tiempo haya pasado.',
    ],
    glossary: [
      { term: 'cajón', translation: 'drawer' },
      { term: 'discusión', translation: 'argument' },
      { term: 'valor', translation: 'courage' },
      { term: 'reconciliarse', translation: 'to reconcile' },
      { term: 'irreversible', translation: 'irreversible' },
      { term: 'dispuesto', translation: 'willing / ready' },
      { term: 'lágrimas', translation: 'tears' },
      { term: 'heridas', translation: 'wounds' },
      { term: 'sanan', translation: 'heal' },
      { term: 'se atreve', translation: 'dares' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'cajón' mean?", choices: ['drawer', 'closet', 'suitcase', 'shelf'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'heridas' mean?", choices: ['wounds', 'memories', 'promises', 'letters'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: "Why hadn't Ricardo and his father spoken?", choices: ['his father moved abroad', 'an argument neither remembered well', 'a disagreement about money', "his father disapproved of his job"], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What made Ricardo finally act?', choices: ["his father's birthday", 'his father becoming seriously ill', "a letter from his mother", "a friend's advice"], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What did Ricardo bring to the hospital?', choices: ['flowers', 'a drawer full of unsent letters', 'a photo album', "his father's medication"], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ["A father and son healing an old wound before it's too late", 'A mystery about missing letters', "A hospital's daily routine", 'A story about moving to a new city'], correctIndex: 0 },
    ],
  },
  {
    id: 'b2-la-decision-de-quedarse',
    title: 'La decisión de quedarse',
    translatedTitle: 'The decision to stay',
    level: 'B2',
    language: 'Spanish',
    nativeLanguage: 'English',
    topic: 'Career & community',
    summary: 'A veterinarian chooses community impact over a lucrative job abroad.',
    paragraphs: [
      'Cuando le ofrecieron un puesto en el extranjero con un salario mucho mejor, Beatriz supuso que aceptaría sin dudarlo. Sin embargo, algo la hizo detenerse.',
      'Llevaba diez años construyendo una pequeña clínica veterinaria en su pueblo, un lugar donde antes no había ningún servicio de este tipo.',
      'Sus pacientes no eran solo animales: también eran las familias que dependían de ella, personas que confiaban en que alguien cuidara de sus mascotas cuando más lo necesitaban.',
      'Beatriz pasó semanas dándole vueltas a la decisión, consciente de que el dinero le permitiría ayudar más a su familia, pero también de que abandonar el pueblo dejaría un vacío difícil de llenar.',
      'Finalmente, habló con un antiguo mentor, quien le recordó que el éxito no siempre se mide en cifras, sino en el impacto que se deja en la vida de los demás.',
      'Beatriz rechazó la oferta y, en cambio, decidió ampliar su clínica contratando a un joven veterinario, asegurando así el futuro del servicio que tanto le había costado construir.',
    ],
    glossary: [
      { term: 'salario', translation: 'salary' },
      { term: 'clínica veterinaria', translation: 'veterinary clinic' },
      { term: 'pacientes', translation: 'patients' },
      { term: 'mascotas', translation: 'pets' },
      { term: 'vacío', translation: 'void / emptiness' },
      { term: 'mentor', translation: 'mentor' },
      { term: 'cifras', translation: 'figures / numbers' },
      { term: 'impacto', translation: 'impact' },
      { term: 'ampliar', translation: 'to expand' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'vacío' mean?", choices: ['void / emptiness', 'opportunity', 'salary', 'celebration'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'ampliar' mean?", choices: ['to expand', 'to close', 'to sell', 'to move'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What was Beatriz offered?', choices: ['a scholarship abroad', 'a better-paying job abroad', 'a bigger house', 'an award'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What has Beatriz built over ten years?', choices: ['a restaurant', 'a veterinary clinic in her town', 'a school', 'a farm'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What did her mentor remind her?', choices: ['that money is the only measure of success', "that success isn't always measured in numbers but in impact", 'that she should take the job', 'that she should retire'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A veterinarian choosing community impact over a lucrative job abroad', 'A story about training a new pet', 'A financial crisis in a small town', 'A romance between two veterinarians'], correctIndex: 0 },
    ],
  },

  /* --------------------------------- C1 --------------------------------- */
  {
    id: 'c1-el-eco-de-una-promesa',
    title: 'El eco de una promesa',
    translatedTitle: 'The echo of a promise',
    level: 'C1',
    language: 'Spanish',
    nativeLanguage: 'English',
    topic: 'Legacy & family',
    summary: "An editor honors a childhood promise by completing her grandfather's unfinished novel.",
    paragraphs: [
      'Cuando era niña, Valeria le había prometido a su abuelo que algún día terminaría de escribir la novela que él dejó inconclusa antes de morir.',
      'Décadas después, convertida ya en una editora reconocida, encontró entre sus pertenencias el manuscrito amarillento, lleno de anotaciones a lápiz y tachones.',
      'Al principio, dudó si tenía derecho a intervenir en una obra ajena, por más que la promesa infantil aún resonara en su memoria como un eco persistente.',
      'Se sumergió, no obstante, en la lectura minuciosa de cada capítulo, tratando de descifrar la voz narrativa que su abuelo había ido perfilando con los años.',
      'A medida que avanzaba, comprendió que terminar la novela no consistía en imponer su propio estilo, sino en honrar fielmente la intención original del autor.',
      'Tras meses de trabajo meticuloso, Valeria publicó la novela bajo ambos nombres, consciente de que había cumplido, por fin, una promesa que trascendía las palabras.',
      'En la presentación del libro, admitió ante el público que escribir aquel final no había sido un acto de creación, sino uno de escucha profunda y paciente.',
    ],
    glossary: [
      { term: 'inconclusa', translation: 'unfinished' },
      { term: 'pertenencias', translation: 'belongings' },
      { term: 'manuscrito', translation: 'manuscript' },
      { term: 'tachones', translation: 'crossed-out marks' },
      { term: 'ajena', translation: "someone else's / foreign" },
      { term: 'minuciosa', translation: 'meticulous, thorough' },
      { term: 'descifrar', translation: 'to decipher' },
      { term: 'perfilando', translation: 'shaping, outlining' },
      { term: 'trascendía', translation: 'transcended' },
      { term: 'meticuloso', translation: 'meticulous' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'inconclusa' mean?", choices: ['unfinished', 'published', 'translated', 'famous'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'trascendía' mean?", choices: ['transcended', 'contradicted', 'replaced', 'shortened'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What promise had Valeria made as a child?', choices: ['to become a writer', "to finish her grandfather's unfinished novel", 'to travel the world', 'to publish her own memoir'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: "What did Valeria find among her grandfather's belongings?", choices: ['a diary', 'a yellowed manuscript full of notes', 'a collection of letters', 'an old typewriter'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What did Valeria realize while working on the novel?', choices: ['she should rewrite it entirely in her own style', "she needed to honor her grandfather's original intention", "the novel wasn't worth finishing", 'she should hire a ghostwriter'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ["An editor honoring a childhood promise by completing her grandfather's unfinished novel", 'A mystery about a stolen manuscript', 'A rivalry between two publishers', 'A story about learning to write'], correctIndex: 0 },
    ],
  },
  {
    id: 'c1-el-precio-del-silencio',
    title: 'El precio del silencio',
    translatedTitle: 'The price of silence',
    level: 'C1',
    language: 'Spanish',
    nativeLanguage: 'English',
    topic: 'Integrity & journalism',
    summary: 'A journalist risks her career to expose the truth about a corrupt public project.',
    paragraphs: [
      'En la redacción del periódico, todos sabían que Elisa era la reportera más tenaz, capaz de desenterrar historias que otros preferían dejar enterradas.',
      'Cuando recibió una filtración anónima sobre irregularidades en la construcción de un puente público, comprendió que aquella investigación podría costarle su empleo.',
      'El director del periódico, presionado por intereses políticos, le advirtió veladamente que publicar el artículo tendría consecuencias difíciles de prever.',
      'Elisa pasó noches enteras verificando cada dato, consciente de que una sola imprecisión bastaría para desacreditar toda la investigación y, con ella, su reputación.',
      'A pesar de las presiones, decidió que el silencio le pesaría más en la conciencia que cualquier represalia profesional que pudiera sufrir por decir la verdad.',
      'El día que se publicó el artículo, varias autoridades fueron destituidas y se abrió una investigación oficial sobre la construcción del puente.',
      'Meses después, aunque perdió su puesto en el periódico, Elisa aceptó que había pagado un precio justo por no traicionar aquello en lo que creía.',
    ],
    glossary: [
      { term: 'redacción', translation: 'newsroom' },
      { term: 'tenaz', translation: 'tenacious' },
      { term: 'desenterrar', translation: 'to unearth' },
      { term: 'filtración', translation: 'leak' },
      { term: 'irregularidades', translation: 'irregularities' },
      { term: 'veladamente', translation: 'in a veiled / subtle way' },
      { term: 'imprecisión', translation: 'inaccuracy' },
      { term: 'desacreditar', translation: 'to discredit' },
      { term: 'represalia', translation: 'retaliation' },
      { term: 'destituidas', translation: 'removed from office' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'tenaz' mean?", choices: ['tenacious', 'careless', 'timid', 'forgetful'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'represalia' mean?", choices: ['retaliation', 'reward', 'promotion', 'apology'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'What did Elisa investigate?', choices: ['a corruption scandal in a hospital', 'irregularities in the construction of a public bridge', 'a fraud at a bank', 'a scandal in city hall elections'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What did the newspaper director do?', choices: ['he encouraged her to publish immediately', 'he subtly warned her of consequences', 'he fired her on the spot', 'he offered her a promotion'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'What happened after the article was published?', choices: ['nothing changed', 'several authorities were removed from office and an investigation opened', 'Elisa was promoted', 'the newspaper shut down'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ['A journalist risking her career to expose the truth about a corrupt public project', 'A love story set in a newsroom', 'A political campaign', 'A story about building a bridge'], correctIndex: 0 },
    ],
  },
  {
    id: 'c1-un-mapa-sin-nombre',
    title: 'Un mapa sin nombre',
    translatedTitle: 'A map without a name',
    level: 'C1',
    language: 'Spanish',
    nativeLanguage: 'English',
    topic: 'Discovery & memory',
    summary: "A man uncovers his great-aunt's secret documentation of a forgotten settlement.",
    paragraphs: [
      'Entre los objetos heredados de su tía abuela, Nicolás encontró un mapa antiguo, dibujado a mano, sin ninguna indicación de lugar ni fecha.',
      'Intrigado por el hallazgo, decidió consultar a un cartógrafo retirado que, tras examinar el papel amarillento, reconoció ciertos rasgos de una región montañosa remota.',
      'Movido por una curiosidad que rayaba en la obsesión, Nicolás organizó una expedición para verificar si el mapa correspondía a un lugar real o era producto de la imaginación de su tía abuela.',
      'Tras días de caminata por senderos apenas transitados, el grupo llegó a un valle escondido que coincidía sorprendentemente con los trazos del mapa original.',
      'Allí descubrieron las ruinas de un pequeño asentamiento, aparentemente abandonado décadas atrás, del cual no existía ningún registro oficial.',
      'Nicolás comprendió entonces que su tía abuela no había dibujado un lugar imaginario, sino que había documentado, en secreto, un rincón del mundo que el tiempo había condenado al olvido.',
      'Al regresar, publicó sus hallazgos en una revista de historia local, devolviendo así, de alguna manera, el nombre perdido a aquel lugar olvidado.',
    ],
    glossary: [
      { term: 'heredados', translation: 'inherited' },
      { term: 'hallazgo', translation: 'discovery, finding' },
      { term: 'cartógrafo', translation: 'cartographer' },
      { term: 'rasgos', translation: 'features' },
      { term: 'rayaba en', translation: 'bordered on' },
      { term: 'senderos', translation: 'paths, trails' },
      { term: 'trazos', translation: 'strokes, lines' },
      { term: 'asentamiento', translation: 'settlement' },
      { term: 'olvido', translation: 'oblivion, forgetting' },
      { term: 'devolviendo', translation: 'returning, giving back' },
    ],
    quiz: [
      { id: 'q1', type: 'vocabulary', prompt: "What does 'hallazgo' mean?", choices: ['discovery', 'mistake', 'memory', 'gift'], correctIndex: 0 },
      { id: 'q2', type: 'vocabulary', prompt: "What does 'olvido' mean?", choices: ['oblivion / forgetting', 'celebration', 'danger', 'treasure'], correctIndex: 0 },
      { id: 'q3', type: 'comprehension', prompt: 'Who did Nicolás consult about the map?', choices: ['a historian', 'a retired cartographer', 'a park ranger', 'his tía abuela'], correctIndex: 1 },
      { id: 'q4', type: 'comprehension', prompt: 'What did the expedition find in the hidden valley?', choices: ['a treasure chest', 'the ruins of an abandoned settlement', 'a new species of animal', 'a modern town'], correctIndex: 1 },
      { id: 'q5', type: 'comprehension', prompt: 'How did Nicolás conclude the story?', choices: ['he sold the map', 'he published his findings in a local history magazine', 'he kept the discovery secret', 'he moved to the valley permanently'], correctIndex: 1 },
      { id: 'q6', type: 'theme', prompt: 'What is this story mainly about?', choices: ["A man uncovering his great-aunt's secret documentation of a forgotten settlement", 'A treasure hunt for gold', 'A story about learning cartography', 'A political conflict over land'], correctIndex: 0 },
    ],
  },
];
